// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { defineConfig, env } from "prisma/config";
import "dotenv/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // CLI-only (migrate/studio). Use the DIRECT session-mode URL — DDL can't run
  // over Supabase's pgbouncer transaction pooler. The app runtime uses
  // DATABASE_URL (pooler) via the PrismaPg adapter in lib/prisma.ts.
  datasource: {
    url: env("DIRECT_URL"),
  },
});
